### ISSUE TITLE
Cypress 12.0.2, 12.1.0+ Integrity check failed

### ISSUE THREAD

**Issue by agoldis** [sorry-cypress/cy2#38]
**UPDATE Jan 09**

Release https://github.com/sorry-cypress/cy2/releases/tag/v4.0.0. Please open new issues as the appear. Closing this one. 

**UPDATE Dec 19**

Try out the new beta versions if the original `cy2` integration:

`npm install cy2@beta`

[Details](https://currents.dev/readme/guides/cypress-compatibility/cypress-12)

---

**UPDATE Dec 16**

We are looking for your feedback and help with testing the new [`cypress-cloud`](https://currents.notion.site/Cypress-12-and-Currents-Sorry-Cypress-3f9f29285f9242c78b0ba63cf9225c6c) integration.

It is compatible with Cypress 12.1.0 (actually all 10.0.0+ packages).

---

**UPDATE Dec 12** 

The new version 12.1.0 has stricter integrity checks and the current integration is not working anymore. 

Hold tight, we are working on a new integration. **Meanwhile please pin the cypress version to 12.0.2 or below** 

--- 

Cypress.io team has released a few breaking changes that can trigger `Integrity check failed` when using cy2. The 
affected version is 12.0.2+

For the majority of cases, `cy2` version 3.4.1 should solve the issue, but depending on your specific use case it may not work.

As an immediate workaround, please downgrade cypress version. We have been working on a fix and an announcement will follow soon.

**Comment by matrunchyk** [comment]
cypress: 12.0.2
os: Linux
cy2: 3.4.2
method: CLI

[See debug log here](https://pastebin.com/CD5TJ7QV)

**Comment by mirobo** [comment]
Additionally the file paths of the manipulated and backed up file in the cy2_injected-method looks wrong on Windows (not sure if it has an impact on functionality):

```
(function cy2_injected() {
    try {
        require('C:/.....whatever......../node_modules/cy2/dist/injected.js'(
        'C:Users\usernameAppDataLocalCypressCache\n.1.0Cypress\resourcesappindex.js',
        'C:Users\usernameAppDataLocalCypressCache\n.1.0Cypress\resourcesappindex.js.bak');
    } catch (e) {
        console.error(e);
    }
}());

```

**Comment by jiadesen** [comment]
cypress 12.1.0
os macos
cy2 3.4.3

```
[cy2] Running cypress with API URL: http://x.x.x.x/
  cy2 Cypress normalized binary path: /Users/projectPath/node_modules/.bin/cypress +0ms
  cy2 Verifying cypress from /Users/projectPath/node_modules/.bin/cypress +1ms
  cy2 Trying discovery via state module +2s
  cy2 Cypress normalized binary path: /Users/projectPath/node_modules/.bin/cypress +5ms
  cy2 Cypress state module candidates: [ '/Users/projectPath/node_modules/.bin/node_modules/cypress/lib/tasks/state.js', '/Users/projectPath/node_modules/lib/tasks/state.js', '/Users/projectPath/node_modules/cypress/lib/tasks/state.js' ] +0ms
  cy2 Cypress state module detected: /Users/projectPath/node_modules/cypress/lib/tasks/state.js +3ms
  cy2 Cypress pkgPath: /Users/xxx/Library/Caches/Cypress/12.1.0/Cypress.app/Contents/Resources/app/package.json +101ms
  cy2 Cypress pkgRoot: /Users/xxx/Library/Caches/Cypress/12.1.0/Cypress.app/Contents/Resources/app +0ms
  cy2 Cypress installation server init: /Users/xxx/Library/Caches/Cypress/12.1.0/Cypress.app/Contents/Resources/app/index.js +0ms
  cy2 Patching cypress entry point file: /Users/xxx/Library/Caches/Cypress/12.1.0/Cypress.app/Contents/Resources/app/index.js +0ms
Error: EPERM: operation not permitted, copyfile '/Users/xxx/Library/Caches/Cypress/12.1.0/Cypress.app/Contents/Resources/app/index.js' -> '/Users/xxx/Library/Caches/Cypress/12.1.0/Cypress.app/Contents/Resources/app/index.js.bak'
    at Object.copyFileSync (node:fs:2847:3)
    at Object.<anonymous> (/Users/projectPath/node_modules/cy2@3.4.3/node_modules/cy2/dist/patch.js:57:25)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/projectPath/node_modules/.pnpm/cy2@3.4.3/node_modules/cy2/dist/patch.js:19:28)
    at _next (/Users/projectPath/node_modules/cy2@3.4.3/node_modules/cy2/dist/patch.js:37:17) {
  errno: -1,
  syscall: 'copyfile',
  code: 'EPERM',
  path: '/Users/xxx/Library/Caches/Cypress/12.1.0/Cypress.app/Contents/Resources/app/index.js',
  dest: '/Users/xxx/Library/Caches/Cypress/12.1.0/Cypress.app/Contents/Resources/app/index.js.bak'
}
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed.
ERROR: "cy2:run" exited with 1.
 ELIFECYCLE  Test failed. See above for more details.
```

**Comment by agoldis** [comment]
@jiadesen Thanks for sharing! Even though 12.1.0 won't work whatsoever, this may be related to https://currents.dev/readme/guides/currents-cli MacOS note

**Comment by jiadesen** [comment]
```
[cy2] Running cypress with API URL: http://10.252.33.180:8089/
Integrity check failed with expected line number 1 but got 79
Error: 
  We detected an issue with the integrity of the Cypress binary. It may have been modified and cannot run. We recommend re-installing the Cypress binary with:
  
  `cypress cache clear && cypress install`
  
    at stackIntegrityCheck (<embedded>:1:1646)
    at integrityCheck (<embedded>:1:5569)
    at Object.<anonymous> (<embedded>:2844:964332)
    at snapshotRequire (evalmachine.<anonymous>:1:749187)
    at runWithSnapshot (evalmachine.<anonymous>:1:757764)
    at hookRequire (evalmachine.<anonymous>:1:758547)
    at startCypress (evalmachine.<anonymous>:1:758979)
    at evalmachine.<anonymous>:1:759290
    at v (/Users/xxx/Library/Caches/Cypress/12.1.0/Cypress.app/Contents/Resources/app/index.js:79:14)
    at Object.<anonymous> (/Users/xxx/Library/Caches/Cypress/12.1.0/Cypress.app/Contents/Resources/app/index.js:84:5)
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed.
ERROR: "cy2:run" exited with 1.
 ELIFECYCLE  Test failed. See above for more details.
```

**Comment by air2** [comment]
Is it maybe an idea to make this package dependent on specific cypress versions, so automatic updaters like dependabot do not upgrade cypress unless cy2 is upgraded?

**Comment by maximilianschmid** [comment]
> Is it maybe an idea to make this package dependent on specific cypress versions, so automatic updaters like dependabot do not upgrade cypress unless cy2 is upgraded?

I prefer to have independent cypress versioning. You can pin your cypress version to a specific version if you do not want to have auto updates. I do have other cypress plugins which are also very restrictive on cypress version requirements, which is most of the time too restrictive and often prevents cypress updates without a reason.

Conclusion: I prefer to have cy2 to not require a specific cypress version. Version pinning is a userland task in my opinion.

**Comment by Jakeii** [comment]
Looks like the integrity check can be disabled by setting `DISABLE_SNAPSHOT_REQUIRE=true`, not sure of the other effects of setting this to true
https://github.com/cypress-io/cypress/blob/c540284f5080d46a8597e53dd2213cb6fb133078/scripts/after-pack-hook.js#L59

**Comment by agoldis** [comment]
@Jakeii doesn't work for me, unfortunately... did you see anything different?

**Comment by mirobo** [comment]
> @Jakeii doesn't work for me, unfortunately... did you see anything different?

For me it "works" ( Retested with 12.0.2 and 12.**2**.0 ), this error message regarding integrity check disappeared, but now there's a new one..

```
starting cypress tests
Running only with Spec File C:\someDir\someSpec.e2e.spec.ts

omeUserAppDataLocalCypressCachedirectory, copyfile 'C:Users
omeUserAppDataLocalCypressCacheUsers
esourcesappindex.js'
    at Object.copyFileSync (node:fs:2817:3)
    at Object.func [as copyFileSync] (node:electron/js2c/asar_bundle:5:1810)
    at module.exports (C:\someDir\node_modules\cy2\dist\injected.js:61:14)
    at cy2_injected (C:\Users\someUser\AppData\Local\Cypress\Cache\12.1.0\Cypress\resources\app\index.js:3:77)
    at Object.<anonymous> (C:\Users\someUser\AppData\Local\Cypress\Cache\12.1.0\Cypress\resources\app\index.js:7:2)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1175:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at c._load (node:electron/js2c/asar_bundle:5:13339) {
  errno: -4058,
  syscall: 'copyfile',
  code: 'ENOENT',
  path: 'C:Users\someUserAppDataLocalCypressCache\n' +
    '.1.0Cypress\resourcesappindex.js.bak',
  dest: 'C:Users\someUserAppDataLocalCypressCache\n.1.0Cypress\resourcesappindex.js'
}


////////// -> new error

Error: Cannot find module './start-cypress'
Require stack:
- C:\Users\someUser\AppData\Local\Cypress\Cache\12.2.0\Cypress\resources\app\packages\server\index.jsc
at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
at n._resolveFilename (node:electron/js2c/browser_init:249:1105)
at Module._load (node:internal/modules/cjs/loader:785:27)
at c._load (node:electron/js2c/asar_bundle:5:13339)
at Module.require (node:internal/modules/cjs/loader:1012:19)
at Mod.require (C:\someDir\node_modules\cy2\dist\injected.js:58:16)
at i (C:\Users\someUser\AppData\Local\Cypress\Cache\12.2.0\Cypress\resources\app\index.js:60:18)
at startCypress (evalmachine.<anonymous>:1:799817)
at evalmachine.<anonymous>:1:800077
at v (C:\Users\someUser\AppData\Local\Cypress\Cache\12.2.0\Cypress\resources\app\index.js:79:14) {
code: 'MODULE_NOT_FOUND',
requireStack: [
'C:\\Users\\someUser\\AppData\\Local\\Cypress\\Cache\\12.2.0\\Cypress\\resources\\app\\packages\\server\\index.jsc'


```

Regarding the error from copyfile, it seems that "acorn" has some issues with backslashes..

https://github.com/sorry-cypress/cy2/blob/68e4c5dded523250ee3445112cb5575dea204fe3/src/js.ts#L16-L29

I was able to fix this with normalizePath, which produces forward slashes (no more escaping issues under windows)

```
export const instrumentCypressInit = (
  code: string,
  injectedModulePath: string,
  entryPointPath: string,
  backupPath: string
) => {
  const normalizedPath = normalizePath(injectedModulePath);
  entryPointPath= normalizePath(entryPointPath);
  backupPath= normalizePath(backupPath);
  const injectedFn = `
function ${FN_ID}() {
    try { require('${normalizedPath}')("${entryPointPath}", "${backupPath}"); }
    catch (e) {
      console.error(e);
    }
}`;

```

Then finally the "copyfile" error disappears.. and the "only" error remaining is the one happening in injected.ts..

```
Error: Cannot find module './start-cypress'
Require stack:
- C:\Users\someUser\AppData\Local\Cypress\Cache\12.2.0\Cypress\resources\app\packages\server\index.jsc
```

It may be caused by this bytecode patch?

https://github.com/cypress-io/cypress/blob/8888cd9e211e608f9bbac81478667b2877dab76e/patches/bytenode%2B1.3.7.dev.patch

**Comment by sebkasanzew** [comment]
I tested the beta version and got the following error in my CI environment:

```
[cy] Using cloud orchestration service: https://xxx.yyy.zzz/
Error: HTTP_PROXY and HTTPS_PROXY are not supported. Please report this issue.
    at E (/builds/.../node_modules/cy2/dist/index.js:5:939)
    at B (/builds/.../node_modules/cy2/dist/index.js:5:1411)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at main (/builds/.../node_modules/cy2/bin/cy2:14:3)
```

cy2: `4.0.0-beta.9`
cypress: `12.2.0`

**Comment by agoldis** [comment]
@sebkasanzew can you please reach out to me privately via Slack or andrew at currents dot dev?

**Comment by agoldis** [comment]
@mirobo please try using `cy2@beta`

**Comment by maximilianschmid** [comment]
4.0.0-beta.9 works with Cypress 12.2.0 on MacOS 13.1.0

**Comment by TchernyavskyDaniil** [comment]
For me i have new issue when try to run in CI:

node_modules/http-proxy/lib/http-proxy/index.js:72
      for(var i=0; i < passes.length; i++) {
                              ^
TypeError: Cannot read properties of undefined (reading 'length')

"http-server": "^14.1.1",

**Comment by fbritoferreira** [comment]
cy2@4.0.0-beta.9 seems to be working fine

**Comment by pkell** [comment]
When using the beta on windows I get this when trying to run from CLI
[cy] Using cloud orchestration service: http://xxx:1234/
Error: spawn C:\Users\paulkelly\source\repos\xxx\Azure\Tests\UI.Tests\node_modules\cypress\bin\cypress ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:285:19)
    at onErrorNT (node:internal/child_process:485:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

When trying programmatically with my script that worked up until version 12 of cypress I always get some version of:
TypeError: patch is not a function

**Comment by agoldis** [comment]
@pkell I am yet to release the documentation for the new version, but `patch` function was deprecated. The module exposes the next API:

### spawn
Spawn a new child `cypress` process, pass down all the flags as-is

```ts
export async function spawn(apiUrl: string) 
```

### run
Run cypress tests programmatically.
- `apiUrl` is the director service URL
- `config` is the same as appears [here](https://docs.cypress.io/guides/guides/module-api#cypress-run)
```ts
async function run(
  apiUrl: string,
  config: CypressCommandLine.CypressRunOptions
)
```

---

> Error: spawn C:\Users\paulkelly\source\repos\xxx\Azure\Tests\UI.Tests\node_modules\cypress\bin\cypress ENOENT

The module needs to resolve the location of cypress correctly, and uses `require.resolve('cypress')` to detect. You can try running with `DEBUG=cy2` to see why isn't it detecting cypress location correctly and do the basic troubleshooting - why isn't the file at the expected location?

**Comment by pkell** [comment]
@agoldis Thanks for the reply.
So after modifying my script to use .run I can run successfully programmatically.
However any attempt to use spawn results in: 
```
Error: spawn C:\Users\paulkelly\source\repos\xxx\Azure\Tests\UI.Tests\node_modules\cypress\bin\cypress ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:285:19)
    at onErrorNT (node:internal/child_process:485:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

This is the same issue I get when trying to run through cli. Not finding anything useful with DEBUG=cy2. I can manually verify the folder and file exists.
```
 [cy2]  Using cloud orchestration service: http://xxx.io:1234/
  cy2 Cypress API URL: http://xxx.io:1234/ +0ms
  cy2 Cypress normalized binary path: C:\Users\paulkelly\source\repos\xxx\Azure\Tests\UI.Tests\node_modules\cypress\bin\cypress +7ms
  cy2 Running cypress from C:\Users\paulkelly\source\repos\xxx\Azure\Tests\UI.Tests\node_modules\cypress\bin\cypress run --record --key XXX --browser edge --parallel --ci-build-id all17 +3ms
  cy2 Proxy environment variables { npm_config_noproxy: '' } +3ms
Error: spawn C:\Users\paulkelly\source\repos\xxx\Azure\Tests\UI.Tests\node_modules\cypress\bin\cypress ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:285:19)
    at onErrorNT (node:internal/child_process:485:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by agoldis** [comment]
@pkell working on a fix...

**Comment by richardmward** [comment]
Just updated to Cypress 12.3.0 and found myself here getting this working again. Largely speaking the `run` command works, but I am finding that the promise is never resolved - e.g. `await run(...)` never returns.

**Comment by agoldis** [comment]
@richardmward please rerun your command with `DEBUG=cypress:*,cy2` to see if its a problem with cy2 or cypress

**Comment by agoldis** [comment]
@pkell should be fixed in [#v4.](https://github.com/sorry-cypress/cy2/releases/tag/v4.0.0)

**Comment by agoldis** [comment]
@sebkasanzew Please checkout the fresh https://github.com/sorry-cypress/cy2/releases/tag/v4.0.0

**Comment by agoldis** [comment]
Please use https://github.com/sorry-cypress/cy2/releases/tag/v4.0.0

**Comment by sebkasanzew** [comment]
Works with [v4.0.1](https://github.com/sorry-cypress/cy2/releases/tag/v4.0.1) for me. Thank you very much @agoldis !

**Comment by pkell** [comment]
Works for me now barring the bug mentioned just above this.
Thanks for all your work @agoldis !
